#!/usr/bin/env python2

from flask import Flask, render_template, request, json
import os

app = Flask(__name__)

@app.route("/")
def main():
    return render_template('index.html')

@app.route("/search", methods=['POST'])
def search():
    _name = request.form['inputName']
    _method = request.form['searchMethod']

    if not _name or not _method:
        return "Wrong data. Please try again."

    if _method == "account":
        os.system("./counterfacto -a " + _name)
    elif _method == "searchterm":
        os.system("./counterfacto -s " + _name)

if __name__ == "__main__":
    try:
        if sys.argv[1] == '-p':
            _port = sys.argv2
    except:
        _port = 5000

    app.run(
        host="0.0.0.0",
        port=int(_port)
    )
